apiVersion: v1
kind: Service
metadata:
  name: warcraider
  labels:
    app: warcraider
spec:
  clusterIP: None
  selector:
    app: warcraider
---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: warcraider
spec: 
  serviceName: warcraider
  selector:
    matchLabels:
      app: warcraider
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: warcraider
    spec: 
      affinity: 
        podAntiAffinity: 
          requiredDuringSchedulingIgnoredDuringExecution: 
            - 
              labelSelector: 
                matchExpressions: 
                  - 
                    key: app
                    operator: In
                    values: 
                      - warcraider
              topologyKey: kubernetes.io/hostname
      containers: 
        - 
          env: 
            - 
              name: RUST_LOG
              value: warcraider
            - name: REPLICAS
              value: "2"
            - 
              name: REPLICA
              valueFrom: 
                fieldRef: 
                  fieldPath: "metadata.labels['statefulset.kubernetes.io/pod-ordinal']"
          image: "gcr.io/dta-ga-bigquery/warcraider"
          imagePullPolicy: Always
          name: warcraider
          resources: 
            limits: 
              cpu: 1000m
              memory: 200M
            requests: 
              cpu: 500m
              memory: 100M
