apiVersion: v1
kind: Service
metadata:
  name: warcraider
  labels:
    app: warcraider
spec:
  clusterIP: None
  selector:
    app: warcraider
---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: warcraider
spec: 
  serviceName: warcraider
  selector:
    matchLabels:
      app: warcraider  
  minReadySeconds: 5
  replicas: 1
  strategy: 
    type: Recreate
  template: 
    metadata: 
      labels: 
        app: warcraider
    spec: 
      affinity: 
        podAntiAffinity: 
          requiredDuringSchedulingIgnoredDuringExecution: 
            - 
              labelSelector: 
                matchExpressions: 
                  - 
                    key: app
                    operator: In
                    values: 
                      - warcraider
              topologyKey: kubernetes.io/hostname
      containers: 
        - 
          env: 
            - 
              name: RUST_LOG
              value: warcraider
            - 
              name: REPLICAS
              value: "3"
            - 
              name: REPLICA
              valueFrom: 
                fieldRef: 
                  fieldPath: "metadata.labels['statefulset.kubernetes.io/pod-ordinal']"
          image: "registry.gitlab.com/bitemyapp/warcraider:latest"
          imagePullPolicy: Always
          name: warcraider
          resources: 
            limits: 
              cpu: 20m
              memory: 20M
            requests: 
              cpu: 10m
              memory: 10M
